Resources:
  URLsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: URLs
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: short_id
          AttributeType: S
      KeySchema:
        - AttributeName: short_id
          KeyType: HASH

  AnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Analytics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: short_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: short_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE